[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
dynamic_padding = true
decorations = "buttonless"
option_as_alt = "Both"

[window.padding]
x = 2
y = 2

# reduce flicker on macos tiling wm setup
# by spawning tiny almost invisible windows
# before they can be picked up by wm
[window.position]
x = 0
y = 0
[window.dimensions]
columns = 1
lines = 1

[keyboard]
bindings = [
  { key = "E", mods = "Alt", action = "ToggleViMode" },
  { mode = "Vi", key = "Escape", action = "ToggleViMode" },
  { mode = "Vi", key = "J", mods = "Shift", action = "ScrollHalfPageDown" },
  { mode = "Vi", key = "K", mods = "Shift", action = "ScrollHalfPageUp" },
]

[general]
import = ["~/.config/alacritty/catppuccin.toml"]
